### ISSUE TITLE
Algorithmic-QuestionNo.8 

### ISSUE THREAD

**Issue by abhijeetgu** [GUSuper60/Algorithmic-Warm-up#1]
`#include<bits/stdc++.h>
using namespace std;

#define ll long long 
int mem[]={0,1,1,2,3,5,8,3,1,4,5,9,4,3,7,0,7,7,4,1,5,6,1,7,8,5,3,8,1,9,0,9,9,8,7,5,2,7,9,6,5,1,6,7,3,0,3,3,6,9,5,4,9,3,2,5,7,2,9,1};

int squarefib(ll n)
{
    ll ans=0;
    ll dif =60;
    ll end = (n%dif);

    for(int i=0;i<=end;i++)
    {
        ll sum = (mem[i]*mem[i])%10;
        ans += sum; 
    }
    return ans%10;
}

int main()
{
    ios_base::sync_with_stdio(0);
    cin.tie(NULL);
    ll n;
    cin>>n;
    cout<<squarefib(n);
    return 0; 
}`

**Comment by ArbitCode** [comment]
Hi @abhijeetgu !
Is there any issue in this code that you have opened closed and reopened after closing
this issue.

**Comment by abhijeetgu** [comment]
It is solution of question no 8.I want it to get it merged here.

**Comment by ArbitCode** [comment]
for this, you need to push this file at `develop` branch as you have already forked this repository. no change branch to develop and commit then push it. 
if there is any issue then `GitHub cheatsheet` is helpful or open this issue.
